DROP TABLE IF EXISTS data CASCADE;


CREATE TABLE data(
    id_data int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    un_text text,
    date_creation TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    active boolean DEFAULT true
);
CREATE OR REPLACE FUNCTION update_ancien_msg() RETURNS VOID AS $$
BEGIN
  UPDATE data
  SET active = false
  WHERE date_creation + (interval '1 minute') <= CURRENT_TIMESTAMP;
END;
$$ LANGUAGE plpgsql;
